name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
#    - name: Build with Gradle
#      run: ./gradlew build
#    - name: assemble package
#      run: ./gradlew layout-builder:assemble
    - name: Print package secrets
      run:
        echo ${{secrets.ENV_VAR}}
        echo ${{secrets.ENV_VAR_TOKEN}}
        echo ${{secrets.ENV_SECRET}}
        echo ${{secrets.ENV_SECRET_TOKEN}}

