name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
#    - name: Build with Gradle
#      run: ./gradlew build
#    - name: assemble package
#      run: ./gradlew layout-builder:assemble
    - name: Print package secrets
      env:
        DEBUG_PASSWORD: ${{  GITHUB_USER_NAME.ENV_VAR }}
        DEBUG_SECRET_KEY: ${{  GITHUB_USER_NAME.ENV_VAR_TOKEN }}
        SECRET_KEY: ${{  GITHUB_USER_NAME.ENV_SECRET }}
        PASSWORD: ${{  GITHUB_USER_NAME.ENV_SECRET_TOKEN }}
      run: |
          echo ${{  GITHUB_USER_NAME.ENV_VAR }} | sed 's/./& /g
          echo ${{  secrets.ENV_VAR }} | sed 's/./& /g'
          echo $DEBUG_SECRET_KEY >> secrets.txt
          echo $SECRET_KEY >> secrets.txt
          echo $PASSWORD >> secrets.txt

